import fs from 'node:fs';
import path from 'node:path';

function elmModuleName(filePath) {
  const base = path.basename(filePath).replace(/\.(tsx|jsx|ts|js)$/, '');
  return base.replace(/[^A-Za-z0-9_]/g, '') || 'Converted';
}

function extractComponentName(source, fallback) {
  const patterns = [
    /export\s+default\s+function\s+([A-Z][A-Za-z0-9_]*)/,
    /function\s+([A-Z][A-Za-z0-9_]*)/,
    /const\s+([A-Z][A-Za-z0-9_]*)\s*=/,
  ];
  for (const pattern of patterns) {
    const match = source.match(pattern);
    if (match) return match[1];
  }
  return fallback;
}

function jsxToElmSketch(jsx) {
  return jsx
    .replace(/className=/g, 'class=')
    .replace(/htmlFor=/g, 'for=')
    .replace(/\{\/\*([\s\S]*?)\*\/\}/g, '--$1')
    .replace(/<>|<React\.Fragment>/g, '<div>')
    .replace(/<\/>|<\/React\.Fragment>/g, '</div>')
    .trim();
}

export function convertReactComponent(source, options = {}) {
  const fallback = options.moduleName ?? 'Converted';
  const componentName = extractComponentName(source, fallback);
  const returnMatch = source.match(/return\s*\(([\s\S]*?)\);?\s*}/m);
  const sketch = returnMatch ? jsxToElmSketch(returnMatch[1]) : 'Text-only component: no JSX return was detected.';

  return `module ${componentName} exposing (view)\n\nimport Html exposing (Html, div, pre, text)\nimport Html.Attributes exposing (class)\n\n{-| Generated by vite.elm's React-to-Elm converter.\n    The converter preserves the JSX as an auditable sketch so the migration can be completed incrementally.\n-}\nview : Html msg\nview =\n    div [ class \"converted-react-component\" ]\n        [ pre [] [ text ${JSON.stringify(sketch)} ] ]\n`;
}

export function convertReactProject(inputDir, outputDir) {
  const converted = [];
  fs.mkdirSync(outputDir, { recursive: true });
  const stack = [inputDir];

  while (stack.length) {
    const current = stack.pop();
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const fullPath = path.join(current, entry.name);
      if (entry.isDirectory()) {
        if (entry.name !== 'node_modules' && entry.name !== 'elm-stuff') stack.push(fullPath);
        continue;
      }
      if (!/\.(tsx|jsx)$/.test(entry.name)) continue;
      const source = fs.readFileSync(fullPath, 'utf8');
      const moduleName = elmModuleName(fullPath);
      const elmSource = convertReactComponent(source, { moduleName });
      const outFile = path.join(outputDir, `${moduleName}.elm`);
      fs.writeFileSync(outFile, elmSource);
      converted.push({ input: fullPath, output: outFile });
    }
  }

  return converted;
}
